# Generated by Django 5.1 on 2024-08-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calories_burned',
            name='calories_burned',
            field=models.DecimalField(decimal_places=6, max_digits=6),
        ),
    ]
