# Generated by Django 5.1 on 2024-08-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_calories_burned_calories_burned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calories_burned',
            name='calories_burned',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
